In [2]:
#Quiz questions

In [4]:
import pandas as pd
import numpy as np

In [5]:
vec = np.array([4,7,8,9,10,6,1])
print(vec[vec>6])

[ 7  8  9 10]


In [6]:
vec1 = np.array([4, 7, 8, 9, 10, 6, 1])
vec1[vec1>6] = 2
print(vec1)

[4 2 2 2 2 6 1]


In [8]:
#working with pandas

In [10]:
demo_array = np.arange(0,10) 

In [11]:
demo_array
demo_array <3
demo_array[demo_array <6]
np.max(demo_array)

9

In [12]:
demo_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
demo_array <3

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [14]:
demo_array[demo_array <6]

array([0, 1, 2, 3, 4, 5])

In [15]:
np.max(demo_array)

9

In [16]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,39,93,39]))

In [17]:
demo_matrix[:, (1,2)]

array([[35, 74],
       [37, 37],
       [39, 93]])

In [18]:
test_array = [10, 11.5, 12, 13.5, 14,15]   

In [19]:
test_array[2:3]

[12]

In [20]:
list_l =[[12,34,55,],[66,45,77],[45,77,88]]

In [21]:
np.array(list_l)

array([[12, 34, 55],
       [66, 45, 77],
       [45, 77, 88]])

In [22]:
score = [10, 15, 20, 25]

In [23]:
pd.Series(data=score, index = ['a','b','c','d'])

a    10
b    15
c    20
d    25
dtype: int64

In [24]:
np.arange(0,22,6)

array([ 0,  6, 12, 18])

In [25]:
demo_array = np.arange(10,21)

In [26]:
subset_demo_array = demo_array[0:7]

In [27]:
subset_demo_array[:]= 101

In [28]:
subset_demo_array

array([101, 101, 101, 101, 101, 101, 101])

In [29]:
flowers = pd.Series([2, 3, 5, 4], index=['lily', 'rose', 'daisy', 'lotus'])

In [30]:
flowers['daisy']

5

In [31]:
dataframe.drop(‘marks’, axis = 1)

SyntaxError: invalid character in identifier (<ipython-input-31-1c1071492b76>, line 1)

In [32]:
s1 = pd.Series(['a', 'b'])

In [33]:
s2 = pd.Series(['c', 'd'])

In [37]:
pd.concat([s1, s2])

0    a
1    b
0    c
1    d
dtype: object

In [38]:
football = [24, 235, 34, 456, 65, 67]

In [39]:
football

[24, 235, 34, 456, 65, 67]

In [40]:
type(football)

list

In [41]:
array = np.array(football)

In [42]:
type(array)

numpy.ndarray

In [46]:
newcolumn = ["A", "B", "C", "D", "E"]

In [47]:
dataframe = pd.Series(data=score, index = ['a','b','c','d'])

In [48]:
dataframe['Alphabets'] = newcolumn

In [49]:
dataframe

a                         10
b                         15
c                         20
d                         25
Alphabets    [A, B, C, D, E]
dtype: object

In [50]:
dataframe['Alphabets']

['A', 'B', 'C', 'D', 'E']

In [51]:
dataframe


a                         10
b                         15
c                         20
d                         25
Alphabets    [A, B, C, D, E]
dtype: object